### ISSUE TITLE
Feature: Main page category and list check

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila-veta#22]
### Modules

- [x] Title - 박상준
- [x] Category - dynamic route - 박상준
- [x] Dropdown - 박상준
- [x] Pagination - 박상준
- [x] Skeleton - Item
- [x] Category Item - 박상준

### Service

- [x] getActivities - dynamic route - 권주현

**Comment by sj0724** [comment]
activityItem card 제작해야합니다!
