### ISSUE TITLE
feat: nextauth v4 server component 에서 사용하기 힘듬.

### ISSUE THREAD

**Issue by jinho0941** [Gila-part4/Gila-veta#27]
v4가 page route기반으로 작성한거라서 server componet에서 session을 가져와서 로그인여부를 채크하는 로직을 작성할려고 보니 server component에서 사용하기가 힘들어 보입니다!

**Comment by sj0724** [comment]
이 부분도 내일 팀미팅 시간에 어떻게 사용할 예정인지 확인해보면 좋을것 같네요..!

**Comment by sj0724** [comment]
https://next-auth.js.org/configuration/nextjs
