### ISSUE TITLE
fix: 로그인 페이지 middleware 작동 안함

### ISSUE THREAD

**Issue by jinho0941** [Gila-part4/Gila-veta#28]
로그인을 하고 auth page로 접근하니까 미들웨어에서 못잡아주는 버그가 있어요! 고쳐주세요

**Comment by sj0724** [comment]
넵 확인해보겠습니다

**Comment by sj0724** [comment]
지금 제 로컬에서는 미들웨어 잘 되는것 같은데 내일 미팅시간에 같이 보면 좋을것 같습니다

**Comment by kuum97** [comment]
이거 환경변수랑 미들웨어 부분 수정하신거 아직 안들어가서 그런거같은데요??

**Comment by sj0724** [comment]
NEXT_PUBLIC_BASE_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=asdfasdfasdf
