### ISSUE TITLE
project total design

### ISSUE THREAD

**Issue by sj0724** [Gila-part4/Gila-veta#3]
- [x] 프로젝트 전체 컨셉

- [x] 서브 컨셉

- [x] 컨셉에 맞는 기능

- [x] 기능에 맞는 기술 스택 및 라이브러리

**Comment by sj0724** [comment]
- 프로젝트 전체 컨셉 : 여행이나 일상에서 사용자에게 상호작용하는 서비스를 제공하는 역할 => **길라잡이** => 서비스 이름 : Gila(길라)
- 프로젝트 서브 컨셉 : 여행에 국한 되는 것이 아니라 여러 사람들을 이어주는 역할(게임 '데스 스트랜딩' 컨셉) => **매듭** => 로고 컨셉 : 매듭

- 컨셉에 맞는 기능 구상 : 당근마켓의 동네생활과 같이 큰 이벤트뿐만아니라 작은 일상 이벤트를 카테고리나 위치로 묶어주기

**Comment by kuum97** [comment]
저희 테일윈드 사용하니까 태블릿 사이즈가 굳이 필요한지 그리고 모바일 퍼스트로 할지도 고민해보고 정하면 어떨까요?
