### ISSUE TITLE
project convention check list

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila-veta#4]
- [x] merge strategy

머지 전략에 저희 코어 타임이나 머지 텀, 리뷰 시간 같은 것들 같이 정해보면 좋을 것 같습니다.

- [x] code

코드 컨벤션에는 특히 타입스크립트 부분을 자세히 정하면 좋을 듯 합니다. (린트 설정과 tsconfig으로 제어 가능)

- [x] naming

전체적으로 폴더 이름이나 함수 이름 등등 가독성이나 팀 프로젝트에 적합한 네이밍을 고민해봅시다.

- [x] commit

커밋 메세지를 통일하고 작은 단위의 커밋을 지향합시다.

- [x] template

PR, issues 생성에 각 상황별 템플릿 정리

**Comment by sj0724** [comment]
airbnb lint, prettier 설정 중

**Comment by sj0724** [comment]
코드 컨벤션내용 위키에 등록함
