### ISSUE TITLE
Issues와 PR템플릿 적용

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila-veta#5]
새로운 이슈나 피알을 생성할 때 간편하게 버그나 기능 추가같은 템플릿을 미리 만들어 두는건 어떨까요??

ex)

### 참고 이미지 또는 링크(선택)

**Comment by sj0724** [comment]
좋아요! 각자 pr올리는 방식이 달라서 템플릿으로 만들어두면 통일되서 좋네요!

**Comment by kuum97** [comment]
그러면 의견 여기에 주시면 좋을 거 같습니다! 아니면 팀회의때 적절한 템플릿 같이 고민해봐두 좋구요!
